In [2]:
import numpy as np

lst = [95., 90., 90., 70, 92, 88, 80]
print(lst)
print(len(lst))
print(type(lst))
print(type(lst[0]))
print(type(lst[4]))

[95.0, 90.0, 90.0, 70, 92, 88, 80]
7
<class 'list'>
<class 'float'>
<class 'int'>


- 리스트에는 각각의 값을 따로따로 저장을 한다.
- array의 경우는 한 번에(연결되어서) 같은 메모리에 저장. -> 데이터 타입이 통일될 수 밖에 없음.

In [3]:
arr = np.array(lst) # 넘파이 배열은 하나의 타입으로 저의가 된다.
print(arr)
print(arr.shape)
print(type(arr))
print(arr.dtype) # 모든 타입이 float64로 통일된다. 따로 자료 지정이 없으면 float64로 지정해주게 된다. 

[95. 90. 90. 70. 92. 88. 80.]
(7,)
<class 'numpy.ndarray'>
float64


## 파이썬 float

- 파이썬 float는 8바이트(64비트)
- float = floating point의 약자 -> 소수점에 **근사** 한 소수(8바이트에 맞춰서 저장)
- floating point는 유효자리 숫자를 보장한다. -> 8바이트는 8자리 유효를 보장
- floating point 사칙연산이 빠른 이유 -> floating point 전용 HW가 들어가있디.(물론 int보다는 느린데) 전용 HW가 들어가있기 때문에 floating point의 가능 용량이 4, 8바이트이다.
- 4바이트(32비트)를 float로 잡아도 상관없다.

## np.array VS np.matrix

In [13]:
# lst1 = [[95, 90, 90], [70, 92, 88]]
# lst2 = [[90, 5, 7], [4, 2, 8], [2, 3, 4]]
lst1 = [[3, 4], [5, 6]]
lst2 = [[10, 20], [30, 40]]
print(np.shape(lst1))

arr1 = np.array(lst1)
arr2 = np.array(lst2)

print('행렬의 곱:\n', np.matmul(arr1, arr2)) 

arr3 = np.matrix(lst1)
arr4 = np.matrix(lst2)
print('각 요소끼리 곱하기:\n', np.multiply(arr3, arr4))

print('행렬의 곱:\n', arr1 @ arr2)
print('각 요소끼리 곱\n', arr1 * arr2) 

print('행렬의 곱:\n', arr3 @ arr4)
print('각 요소끼리 곱?\n', arr3 * arr4) # matrix의 경우는 @, * 모두 행렬의 곱을 나타낸다.

## 결론 -> matrix는 사용하지 않는다. 보통 array를 사용하고 행렬의 곱 연산자는 @를 사용한다.


(2, 2)
배열끼리 곱하기:
 [[150 220]
 [230 340]]
각 요소끼리 곱하기:
 [[ 30  80]
 [150 240]]
행렬의 곱:
 [[150 220]
 [230 340]]
각 요소끼리 곱
 [[ 30  80]
 [150 240]]
행렬의 곱:
 [[150 220]
 [230 340]]
각 요소끼리 곱?
 [[150 220]
 [230 340]]


## numpy의 두 가지 형태

- np. ~
- arr. ~

In [5]:
# np. ~
arr1 = np.arange(16)
arr2 = np.reshape(arr1, (4, 4))
print(arr1)
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [6]:
# arr. ~
arr1 = np.arange(16)
arr2 = arr1.reshape(4, 4)
print(arr1)
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


## np.reshpae

In [15]:
arr1 = np.arange(8)
print(arr1)

arr2 = np.reshape(arr1, (2, -1)) # -1 -> 나머지 요소 개수를 알아서 정의해줘
print(arr2)
# 만약에 개수가 맞지 않으면 에러가 난다

[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]


In [19]:
arr1 = np.arange(12)
arr2 = arr1.reshape(2, -1)
print(arr1)
print(arr2)

print(arr1[0])
print(arr2[0]) # 2차원 배열이니까 0번째 인덱스는 넘파이 배열이 된당
print('넘파이적 사고로 0번째 배열 출력하기:', arr2[0, :])
print(arr2[0, 0])
# 넘파이 arange로 만들면 메모리 공간을 12개를 연속으로 만드는데(크기랑 상관없음(3차원이더라도 연속으로 메모리 할당)), reshape를 하게 되면 메모리에 다시 할당된게 아니라 다른 변수명의 point가 같다. 실제로 값을 저장하는 곳은 동일한데, 변수마다 shape를 저장하는 공간은 따로 있다. 
# 변수마다 크기와 메모리 할당 위치만 저장이 된다. -> deep copy 의 필요성

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
0
[0 1 2 3 4 5]
넘파이적 사고로 0번째 배열 출력하기: [0 1 2 3 4 5]
0


## deep copy

In [23]:
arr1 = np.arange(12)
arr2 = arr2.reshape(2, -1)
arr3 = arr1[2:10]
arr4 = arr2.copy()

arr2[0, 0] = 10

print(arr1)
print(arr2)
print('arr1 메모리 공간을 가리키고 있음:', arr3)
print('arr2와 다른 공간을 가리키고 있음:\n', arr4)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[10  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
arr1 메모리 공간을 가리키고 있음: [2 3 4 5 6 7 8 9]
arr2와 다른 공간을 가리키고 있음:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


## indexing

In [25]:
arr1 = np.arange(16)
arr2 = arr1.reshape(4, -1)

print(arr2)
print(arr2[1, 3])
print(arr2[0, 1])
print(arr2[2, 2])

print(arr2[[1, 0, 2], [3, 1, 2]]) # 요소 한 번에 뽑기 arr2[1, 3], arr2[0, 1], arr2[2, 2] 각각 출력해줌.

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
7
1
10
[ 7  1 10]


## slicing

In [26]:
arr = np.arange(16).reshape(4, 4)

print(arr) # 시작하는 위치를 집음
print(arr[1:3, 1:3])
print(arr[:, :]) # 데이터 그 자체를 집음, 순수하게 데이터끼리 copy할 때
print(arr[1:, :-1]) # 마지막 열 포함 아님.

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 5  6]
 [ 9 10]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
